server:
  port: 8080
  servlet:
    context-path: '/api/'
  error:
    include-stacktrace: never
spring:
  application:
    name: Voll Med Api
  datasource:
    url: jdbc:postgresql://localhost:5432/vollmed_api
    username: myuser
    password: secret
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}